name: ⬣ Lint

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: actions/cache/restore@v4
      id: restore-cache
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - run: nix develop --command pnpm install
    - run: nix develop --command pnpm lint
    - run: nix develop --command pnpm build

    - name: Get pnpm cache directory
      id: pnpm-store-dir
      shell: bash
      run: echo "dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

    - uses: actions/cache/save@v4
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.pnpm-store-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-
